---
- name: fail on unsupported distribution for iscsi gateways
  fail:
    msg: "iSCSI gateways can only be deployed on Red Hat Enterprise Linux, CentOS or Fedora"
  when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Fedora']

- name: fail on unsupported distribution version for iscsi gateways
  command: "grep -q {{ item }}=m {% if is_atomic|bool %}/usr/lib/ostree-boot{% else %}/boot{% endif %}/config-{{ ansible_facts['kernel'] }}"
  register: iscsi_kernel
  changed_when: false
  failed_when: iscsi_kernel.rc != 0
  loop:
    - CONFIG_TARGET_CORE
    - CONFIG_TCM_USER2
    - CONFIG_ISCSI_TARGET
  when: ansible_facts['distribution'] in ['RedHat', 'CentOS']
